# Stage 4. Tensor의 연산

# 1. 기본 연산
## 1.1. Tensor와 Scalar의 연산
PyTorch에서 Tensor와 Scalar(단일 숫자)간의 사칙연산은 지원됩니다. Tensor와 Scalar 사이의 덧셈 연산을 수행할 때, Scalar 값은 Tensor의 모든 요소에 대해 적용됩니다. \
\
연산 방법은 Python과 동일합니다.
- 덧셈: +
- 뺄셈: -
- 곱셈: *
- 나눗셈: /
- 제곱: **

In [3]:
import torch

tensor = torch.tensor([[1, 2], [3, 4]], dtype=torch.float32)

# Tensor와 Scalar의 덧셈
add_scalar = tensor + 1

# Tensor와 Scalar의 뺄셈
sub_scalar = tensor - 1

# Tensor와 Scalar의 곱셈
mul_scalar = tensor * 2

# Tensor와 Scalar의 나눗셈
div_scalar = tensor / 2

# Tensor와 Scalar의 제곱
pow_scalar = tensor ** 2

print('Scalar 덧셈: \n', add_scalar)
print('Scalar 뺄셈: \n', sub_scalar)
print('Scalar 곱셈: \n', mul_scalar)
print('Scalar 나눗셈: \n', div_scalar)
print('Scalar 제곱: \n', pow_scalar)

Scalar 덧셈: 
 tensor([[2., 3.],
        [4., 5.]])
Scalar 뺄셈: 
 tensor([[0., 1.],
        [2., 3.]])
Scalar 곱셈: 
 tensor([[2., 4.],
        [6., 8.]])
Scalar 나눗셈: 
 tensor([[0.5000, 1.0000],
        [1.5000, 2.0000]])
Scalar 제곱: 
 tensor([[ 1.,  4.],
        [ 9., 16.]])


## 1.2. 덧셈과 뺄셈
Tensor의 덧셈과 뺄셈 연산은 두 Tensor의 동일 위치에 있는 요소들 끼리 연산을 수행합니다.\
\
예를 들어, 두 개의 2x2 텐서 tensor_a와 tensor_b는 각각 [[1,2],[3,4]]와 [[5,6],[7,8]]의 값을 갖을 때, 이 둘의 연산은 아래와 같이 계산됩니다.
- 덧셈 결과: 각 요소를 더한 결과인 [[6,8],[10,12]]를 얻습니다. 이는 tensor_a의 각 요소에 tensor_b의 해당 요소를 더하여 계산된 결과입니다.
- 뺄셈 결과: tensor_a에서 tensor_b를 뺀 결과인 [[-4,-4],[-4,-4]]를 얻습니다. 이는 tensor_a의 각 요소에서 tensor_b의 해당 요소를 빼서 계산된 결과입니다. 

In [4]:
tensor_a = torch.tensor([[1,2], [3,4]])
tensor_b = torch.tensor([[5,6], [7,8]])

# Tensor 덧셈
add_result = tensor_a + tensor_b
# 또는 torch.add(tensor_a, tensor_b)를 사용할 수 있습니다.

# Tensor 뺄셈
sub_result = tensor_a - tensor_b
# 또는 torch.sub(tensor_a, tensor_b)를 사용할 수 있습니다.

print('덧셈 결과: \n', add_result)
print('뺄셈 결과: \n', sub_result)

덧셈 결과: 
 tensor([[ 6,  8],
        [10, 12]])
뺄셈 결과: 
 tensor([[-4, -4],
        [-4, -4]])


## 1.3. 곱셈과 나눗셈
요소별 곱셈과 나눗셈 연산도 마찬가지로 각 텐서의 동일한 위치에 있는 요소끼리 수행됩니다.\
\
예를 들어, tensor_a와 tensor_b는 각각 [2,3,4]와 [5,6,7]의 값을 갖는 Tensor입니다. 연산 결과는 다음과 같습니다.
- 요소별 곱셈 결과: 각 요소의 곱셈 결과인 [10, 18, 28]을 얻습니다.
- 요소별 나눗셈 결과: 각 요소를 나눈 결과인 [0.4, 0.5, 0.5714...]를 얻습니다.