# 1. Tensor의 형태 변환
## 1.1. Tensor의 형태 변경 - reshape
reshape()함수는 Tensor의 형태를 변경하는 데 사용됩니다. 이 함수는 원본 Tensor의 data를 유지하면서 새로운 형태의 Tensor를 반환합니다. \
\
reshape()는 주어진 새로운 형태가 원본 Tensor의 총 원소 수와 일치할 때 사용할 수 있습니다. 이는 data의 차원을 재구성하거나, 특정 연산에 적합한 형태로 Tensor를 조정할 필요가 있을 때 매우 유용합니다. \
\
만약 변경하려는 형태가 원본 Tensor의 data와 호환되면, PyTorch는 가능한 한 원본 data를 공유하려고 시도합니다. 만약 원본 Tensor의 memory layout이 연속적이지 않아서 직접적인 형태 변경이 불가능한 경우, reshape()는 먼저 Tensor의 data를 복사하여 memory상에서 연속적인 형태로 만든 다음 형태를 변경합니다. 이는 추가적인 memory 사용과 계산 비용을 발생시킬 수 있습니다.

In [2]:
import torch

# 초기 텐서 생성
x = torch.arange(16)    # 0에서 15까지의 숫자를 포함하는 텐서
print("텐서: ", x)
print("텐서의 형태: ", x.shape)

# reshape 함수 사용 예제
reshaped_x = x.reshape(4, 4)    # 4x4 텐서로 변경
print("\n변형 후 텐서:\n", reshaped_x)
print("변형 후 텐서의 형태: ", reshaped_x.shape)

텐서:  tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])
텐서의 형태:  torch.Size([16])

변형 후 텐서:
 tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]])
변형 후 텐서의 형태:  torch.Size([4, 4])


## 1.2. Tensor의 형태 변경 - view
view()함수는 원본 Tensor의 data를 공유하는 새로운 형태의 Tensor를 반환합니다. 이는 data의 실제 memory layout을 변경하지 않으며, 단지 Tensor에 대한 새로운 index view를 제공합니다. \
\
만약 원본 Tensor가 memory상에서 연속적이지 않은 경우, view()함수는 오류를 발생시킵니다. 이런 상황에서는 reshape()함수를 사용하거나, contiguous() 메소드를 호출한 후 view()를 사용해야 합니다. 

In [ ]:
viewed_x = x.view(4, 2, 2)  # 4x2x2 텐서롤 변경
print("변형 후 텐서:\n", viewed_x)
print("변형 후 텐서의 형태: ", viewed_x.shape)

변형 후 텐서:  tensor([[[ 0,  1],
         [ 2,  3]],

        [[ 4,  5],
         [ 6,  7]],

        [[ 8,  9],
         [10, 11]],

        [[12, 13],
         [14, 15]]])
변형 후 텐서의 형태:  torch.Size([4, 2, 2])


# 1.3. 차원 축소 - squeeze
squeeze함수는 Tensor에서 크기가 1인 차원을 찾아서 그 차원을 제거합니다. 이는 data의 형태를 바꾸지 않으면서 Tensor를 더 효율적으로 만들어 줍니다. \
\
예를 들어, 만약 여러분이 [1, 10, 1, 50] 크기의 Tensor를 가지고 있다면, sqeeze를 사용한 후에는 [10, 50] 크기의 Tensor를 얻게 됩니다.

In [ ]:
# 크기가 1인 차원을 포함하는 텐서 생성
tensor = torch.tensor([[[1, 2, 3, 4]]])     # 크기: (1, 1, 4)
print("원본 텐서: ", tensor)
print("원본 텐서 형태: ", tensor.shape)

# 모든 크기가 1인 차원을 제거
squeezed_tensor = tensor.squeeze()
print("\n변형된 텐서: ", squeezed_tensor)
print("변형된 텐서 형태: ", squeezed_tensor.shape)

# 특정 차원을 지정하여 squeeze
squeezed_dim_tensor = tensor.squeeze(0)     # 첫 번째 차원을 지정
print("\n변형된 텐서: ", squeezed_dim_tensor)
print("변형된 텐서 형태: ", squeezed_dim_tensor.shape)

원본 텐서:  tensor([[[1, 2, 3, 4]]])
원본 텐서 형태:  torch.Size([1, 1, 4])

변형된 텐서:  tensor([1, 2, 3, 4])
변형된 텐서 형태:  torch.Size([4])

변형된 텐서:  tensor([[1, 2, 3, 4]])
변형된 텐서 형태:  torch.Size([1, 4])


## 1.4. 차원 확장 - unsqueeze
squeeze가 상자에서 불필요한 공간을 제거한다면, unsqueeze는 상자에 조금 더 공간을 추가하는 것과 비슷합니다. PyTorch에서 unsqueeze함수는 지정된 위치에 새로운 차원을 추가합니다. 이것은 data의 형태를 바꾸는 방법으로 특정 연산을 수행하기 위해 data의 차원을 조정해야 할 때 유용합니다. \
\
예를 들어, [10, 50] 크기의 Tensor에 unsqueeze를 사용하여 첫 번째 위치에 차원을 추가하면, [1, 10, 50]의 크기를 가진 Tensor가 됩니다.

In [9]:
# 원본 텐서 생성
tensor = torch.tensor([1, 2, 3, 4])     # 크기: (4,)
print("원본 텐서: ", tensor)
print("원본 텐서 형태: ", tensor.shape)

# 첫 번째 차원을 추가하여 차원 확장
unsqueeze_tensor_first_dim = tensor.unsqueeze(0)
print("\n변형된 텐서: ", unsqueeze_tensor_first_dim)
print("변형된 텐서 형태: ", unsqueeze_tensor_first_dim.shape)

# 마지막 차원을 추가하여 차원 확장
unsqueeze_tensor_last_dim = tensor.unsqueeze(-1)
print("\n변형된 텐서:\n", unsqueeze_tensor_last_dim)
print("변형된 텐서 형태:\n", unsqueeze_tensor_last_dim)

원본 텐서:  tensor([1, 2, 3, 4])
원본 텐서 형태:  torch.Size([4])

변형된 텐서:  tensor([[1, 2, 3, 4]])
변형된 텐서 형태:  torch.Size([1, 4])

변형된 텐서:
 tensor([[1],
        [2],
        [3],
        [4]])
변형된 텐서 형태:
 tensor([[1],
        [2],
        [3],
        [4]])


## 1.5. Tensor의 차원 교환 - transpose
transpose 함수는 여러분이 책장을 정리하다가 책들을 가로로 놓은 것을 세로로 바꾸고 싶을 때와 비슷한 일을 합니다. \
즉, Tensor의 두 차원을 서로 바꾸는 역할을 합니다. 이는 matrix의 행과 열을 바꾸는 것과 유사하며, data를 다른 방식으로 해석하고 싶을 때 매우 유용합니다. \
\
예를 들어, [10, 50] 크기의 Tensor에 대해 첫 번째 차원과 두 번째 차원을 transpose하면, [50, 10] 크기의 Tensor를 얻게 됩니다.

In [10]:
# 초기 3차원 텐서 생성
tensor = torch.rand(2, 3, 4)

transposed_tensor = tensor.transpose(0, 1)  # 첫 번째 차원과 두 번째 차원 교환
print("변형된 텐서 형태: ", transposed_tensor.shape)

변형된 텐서 형태:  torch.Size([3, 2, 4])


# 1.6. Tensor의 차원 교환 - permute
permute 함수는 여러분이 방의 가구를 재배치하여 완전히 새로운 공간을 만들고 싶을 때와 비슷한 작업을 합니다.\
이 함수는 Tensor의 차원을 재배열할 수 있게 해줍니다. permute는 여러 차원을 한 번에 자유롭게 바꾸고 싶을 때 사용합니다.\
\
예를 들어, [10, 20, 30] 크기의 Tensor가 있을 때, permute를 사용하여 차원의 순서를 [2, 0, 1]로 바꾸면, [30, 10, 20] 크기의 새로운 형태의 Tensor를 얻게 됩니다.

In [11]:
# permute 사용 예제
permuted_tensor = tensor.permute(2, 0, 1)   # 차원 순서를 (2, 0, 1)로 재배열
print("변형된 텐서 형태: ", permuted_tensor)

변형된 텐서 형태:  tensor([[[0.0593, 0.8689, 0.4752],
         [0.5843, 0.2659, 0.4707]],

        [[0.4275, 0.2822, 0.3125],
         [0.4996, 0.2846, 0.9351]],

        [[0.4274, 0.7029, 0.4659],
         [0.8599, 0.7070, 0.6709]],

        [[0.2231, 0.6980, 0.0773],
         [0.7189, 0.5682, 0.3694]]])


# 2. Tensor의 결합과 분할
## 2.1. Tenosr 결합 - cat
cat 함수는 'concatenate(연결)'의 줄임말입니다. 마치 여러분이 친구들과 손을 잡고 줄을 서는 것처럼, cat 함수는 여러 Tensor를 지정된 차원을 따라 하나로 연결합니다.\
이를 통해 크기가 더 큰 새로운 Tensor를 생성할 수 있습니다. cat은 여러 data 조각을 하나로 모으고 싶을 때 매우 유용합니다.\
\
예를 들어, [2, 2] 및 [2, 3] 크기의 두 Tensor를 1번째 차원(열)을 따라 연결하면, [2, 5] 크기의 Tenosr가 만들어집니다.

In [13]:
# 두 개의 텐서 생성
tensor1 = torch.tensor([[1, 2], [3, 4]])
tensor2 = torch.tensor([[5, 6, 7], [8, 9, 10]])

# cat 함수 사용 예제
cat_tensors = torch.cat((tensor1, tensor2), dim=1)  # 1번 차원(열)을 따라 결합
print("결합된 텐서:\n", cat_tensors)

print('\ntensor1 텐서 형태: ', tensor1.shape)
print('tensor2 텐서 형태: ', tensor2.shape)
print('cat_tensors 텐서 형태: ', cat_tensors.shape)

결합된 텐서:
 tensor([[ 1,  2,  5,  6,  7],
        [ 3,  4,  8,  9, 10]])

tensor1 텐서 형태:  torch.Size([2, 2])
tensor2 텐서 형태:  torch.Size([2, 3])
cat_tensors 텐서 형태:  torch.Size([2, 5])


## 2.2. Tensor 결합 - stack
stack 함수는 여러분이 책을 쌓아 올리듯이, 여러 Tensor를 새로운 차원을 추가하여 쌓아 올립니다.\
이는 cat과 다르게, 모든 Tensor에 대해 새로운 차원이 생기므로, Tenosor들은 그 크기가 동일해야만 합니다.\
stack은 data를 구조적으로 정리하고 싶을 때 유용합니다.\
\
예를 들어, 세 개의 [2, 2] 크기의 Tenosor를 stack으로 쌓으면, [3, 2, 2] 크기의 Tensor가 됩니다.

In [ ]:
# 2x2 Matrix 생성
tensor1 = torch.tensor([[1, 2], [3, 4]])
tensor2 = torch.tensor([[5, 6], [7, 8]])
tensor3 = torch.tensor([[9, 10], [11, 12]])

# stack