# Stage 4. Tensor의 연산

# 1. 기본 연산
## 1.1. Tensor와 Scalar의 연산
PyTorch에서 Tensor와 Scalar(단일 숫자)간의 사칙연산은 지원됩니다. Tensor와 Scalar 사이의 덧셈 연산을 수행할 때, Scalar 값은 Tensor의 모든 요소에 대해 적용됩니다. \
\
연산 방법은 Python과 동일합니다.
- 덧셈: +
- 뺄셈: -
- 곱셈: *
- 나눗셈: /
- 제곱: **

In [2]:
import torch

tensor = torch.tensor([[1, 2], [3, 4]], dtype=torch.float32)

# Tensor와 Scalar의 덧셈
add_scalar = tensor + 1

# Tensor와 Scalar의 뺄셈
sub_scalar = tensor - 1

# Tensor와 Scalar의 곱셈
mul_scalar = tensor * 2

# Tensor와 Scalar의 나눗셈
div_scalar = tensor / 2

# Tensor와 Scalar의 제곱
pow_scalar = tensor ** 2

print('Scalar 덧셈: \n', add_scalar)
print('Scalar 뺄셈: \n', sub_scalar)
print('Scalar 곱셈: \n', mul_scalar)
print('Scalar 나눗셈: \n', div_scalar)
print('Scalar 제곱: \n', pow_scalar)

Scalar 덧셈: 
 tensor([[2., 3.],
        [4., 5.]])
Scalar 뺄셈: 
 tensor([[0., 1.],
        [2., 3.]])
Scalar 곱셈: 
 tensor([[2., 4.],
        [6., 8.]])
Scalar 나눗셈: 
 tensor([[0.5000, 1.0000],
        [1.5000, 2.0000]])
Scalar 제곱: 
 tensor([[ 1.,  4.],
        [ 9., 16.]])


## 1.2. 덧셈과 뺄셈
Tensor의 덧셈과 뺄셈 연산은 두 Tensor의 동일 위치에 있는 요소들 끼리 연산을 수행합니다.\
\
예를 들어, 두 개의 2x2 텐서 tensor_a와 tensor_b는 각각 [[1,2],[3,4]]와 [[5,6],[7,8]]의 값을 갖을 때, 이 둘의 연산은 아래와 같이 계산됩니다.
- 덧셈 결과: 각 요소를 더한 결과인 [[6,8],[10,12]]를 얻습니다. 이는 tensor_a의 각 요소에 tensor_b의 해당 요소를 더하여 계산된 결과입니다.
- 뺄셈 결과: tensor_a에서 tensor_b를 뺀 결과인 [[-4,-4],[-4,-4]]를 얻습니다. 이는 tensor_a의 각 요소에서 tensor_b의 해당 요소를 빼서 계산된 결과입니다. 

In [3]:
tensor_a = torch.tensor([[1,2], [3,4]])
tensor_b = torch.tensor([[5,6], [7,8]])

# Tensor 덧셈
add_result = tensor_a + tensor_b
# 또는 torch.add(tensor_a, tensor_b)를 사용할 수 있습니다.

# Tensor 뺄셈
sub_result = tensor_a - tensor_b
# 또는 torch.sub(tensor_a, tensor_b)를 사용할 수 있습니다.

print('덧셈 결과: \n', add_result)
print('뺄셈 결과: \n', sub_result)

덧셈 결과: 
 tensor([[ 6,  8],
        [10, 12]])
뺄셈 결과: 
 tensor([[-4, -4],
        [-4, -4]])


## 1.3. 곱셈과 나눗셈
요소별 곱셈과 나눗셈 연산도 마찬가지로 각 텐서의 동일한 위치에 있는 요소끼리 수행됩니다.\
\
예를 들어, tensor_a와 tensor_b는 각각 [2,3,4]와 [5,6,7]의 값을 갖는 Tensor입니다. 연산 결과는 다음과 같습니다.
- 요소별 곱셈 결과: 각 요소의 곱셈 결과인 [10, 18, 28]을 얻습니다.
- 요소별 나눗셈 결과: 각 요소를 나눈 결과인 [0.4, 0.5, 0.5714...]를 얻습니다.

In [4]:
# 두 Tensor 생성
tensor_a = torch.tensor([2, 3, 4], dtype=torch.float32)
tensor_b = torch.tensor([5, 6, 7], dtype=torch.float32)

# 요소별 곱셈
product = tensor_a * tensor_b
# 또는 torch.mul(tensor_a, tensor_b)를 사용할 수 있습니다.
print('요소별 곱셈: ', product)

# 요소별 나눗셈
division = tensor_a / tensor_b
# 또는 torch.div(tensor_a, tensor_b)를 사용할 수 있습니다.
print('요소별 나눗셈: ', division)

요소별 곱셈:  tensor([10., 18., 28.])
요소별 나눗셈:  tensor([0.4000, 0.5000, 0.5714])


## 1.4. Broadcasting 이해하기
Broadcasting을 통해 서로 다른 shape을 가진 Tensor들 간에도 수학 연산을 수행할 수 있게 됩니다. 이는 더 작은 Tensor가 큰 Tensor의 모양에 맞게 자동으로 확장(확대)되어 연산이 가능하게 만듭니다. \
\
Broadcasting이 작동하는 방법은 다음과 같은 규칙을 따릅니다.
1. 차원의 크기가 같거나, 하나의 차원이 1인 경우에만 Broadcasting이 가능합니다. 예를 들어, (5, 4) 모양의 Tensor와 (1, 4) 모양의 Tensor는 Broadcasting이 가능합니다. 여기서 (1, 4) 모양의 Tensor는 첫 번째 차원을 따라 5회 반복되어 (5, 4) 모양으로 확장됩니다.
2. Tensor의 차원 수가 다를 경우, 더 작은 차원을 가진 Tensor의 모양 앞에 1을 추가하여 차원의 수를 맞춥니다. 예를 들어, (5, 4) 모양의 Tensor와 (4,) 모양의 Tensor가 있을 때, 더 작은 Tensor는 (1, 4)로 간주됩니다. 그 후, 앞서 설명한 바와 같이 Broadcasting이 수행됩니다.
3. Broadcasting은 각 차원을 따라 반복함으로써 더 큰 모양의 Tensor에 맞추어 확장합니다. 이 과정은 실제 data 복사가 일어나지 않으며, 연산을 효율적으로 만들기 위한 가상의 확장으로 생각할 수 있습니다.

In [5]:
# 크기가 (1, 3)인 Tensor 생성
tensor_a = torch.tensor([[1, 2, 3]], dtype=torch.float32)  

# 크기가 (3,)인 Tensor 생성
tensor_b = torch.tensor([4, 5, 6], dtype=torch.float32)   

# tensor_a와 tensor_b의 요소별 덧셈 (Broadcasting 발생)
# tensor_b가 tensor_a의 모양에 맞게 확장되어 연산됨
result_add = tensor_a + tensor_b
print('요소별 덧셈 결과: \n', result_add)

요소별 덧셈 결과: 
 tensor([[5., 7., 9.]])


# 2. 비교 연산
## 2.1. 동등 비교
동등 비교는 두 Tensor 간의 요소별 동등성을 비교하는 데 사용하는 것입니다. \
\
동등비교를 위해 ==또는 torch.eq()를 사용합니다. 이 함수는 두 Tensor의 동일한 위치에 있는 요소가 같은지 여부를 검사하고, 결과를 Boolean Tensor로 반환합니다. 즉, 두 요소가 같으면 True, 다르면 False 값을 갖습니다. \
\
torch.eq() 함수의 사용법은 매우 간단합니다. 두 Tensor a와 b가 주어졌을 때, torch.eq(a, b)를 호출하여 두 Tensor 간의 요소별 동등 비교를 수행할 수 있습니다.

In [6]:
tensor_a = torch.tensor([1, 2, 3, 4, 5])
tensor_b = torch.tensor([1, 2, 0, 4, 5])

result = tensor_a == tensor_b
# torch.eq(tensor_a, tensor_b)를 사용할 수 있습니다.

print('동등 비교 결과: ', result)

동등 비교 결과:  tensor([ True,  True, False,  True,  True])


## 2.2. 대소 비교(1) - 크다/작다
동등 비교는 두 Tensor 간의 요소별 동등성을 비교하는 데 사용하는 것입니다. \
\
동등 비교를 위해 == 또는 torch.eq()를 사용합니다. 이 함수는 두 Tensor의 동일한 위치에 있는 요소가 같은지 여부를 검사하고, 결과를 Boolean Tensor로 반환합니다. 즉, 두 요소가 같으면 True, 다르면 False 값을 갖습니다. \
\
torch.eq() 함수의 사용법은 매우 간단합니다. 두 Tensor a와 b가 주어졌을 때, torch.eq(a, b)를 호출하여 두 Tensor 간의 요소별 동등 비교를 수행할 수 있습니다.

In [7]:
tensor_a = torch.tensor([5, 6, 7, 8])
tensor_b = torch.tensor([4, 6, 7, 10])

# 조건: a 텐서가 b 텐서보다 크다
gt_result = tensor_a > tensor_b
# 또는 torch.gt(tensor_a, tensor_b)를 사용할 수 있습니다.

# 조건: a 텐서가 b 텐서보다 작다
lt_result = tensor_a < tensor_b
# 또는 torch.lt(tensor_a, tensor_b)를 사용할 수 있습니다.

print('a가 b보다 큰가: ', gt_result)
print('a가 b보다 작은가: ', lt_result)

a가 b보다 큰가:  tensor([ True, False, False, False])
a가 b보다 작은가:  tensor([False, False, False,  True])
