# 1. 텐서의 기본 개념 및 생성 (1)
### Tensor란 무엇인가
Tensor는 data를 다차원 배열로 일반화한 것입니다. 수학적으로는 scalar, vector, matrix을 고차원으로 확장한 개념으로 볼 수 있으며, 딥러닝에서는 이러한 Tensor를 사용하여 복잡한 data 구조를 효율적으로 처리합니다. \
예를 들어, 0차원 Tensor는 단일 숫자(scalar)를, 1차원 Tensor는 숫자의 배열(vector)를, 2차원 Tensor는 숫자의 2차원 배열(matrix)을 나타내며, 이를 더 확장하여 Image Data(3차원 Tensor) or Video Data(4차원 Tensor) 등을 처리할 수 있습니다.
### Tensor의 중요성
Tensor는 Deeplearning model에서 data를 표현하고 처리하는 핵심적인 구성 요소입니다. 모든 Deeplearning 연산은 Tensor를 사용하여 수행되며, 이는 복잡한 Data Structurer를 효율적으로 다루기 위해 필수적입니다. Tensor를 사용함으로써 다음과 같은 이점을 얻을 수 있습니다
- 다차원 데이터 처리: Tensor를 사용하면 image, video, text 등 다양한 형태의 고차원 data를 쉽게 처리할 수 있습니다.
- 벡터화 연산: Tensor를 통한 벡터롸 연산은 계산 효율성을 높이고, 코드의 간결성을 유지할 수 있게 해줍니다.
- GPU 가속: 대부분의 Deeplearning Library는 Tensor 연산을 GPU에서 실행할 수 있게 지원하여, 대규모 dataset의 처리 속도를 크게 향상시킵니다. 
### PyTorch에서의 Tensor
PyTorch는 Tensor를 기반으로 Deeplearning model을 구축하고 학습합니다. PyTorch에서 Tensor는 torch.Tensor 클래스로 표현됩니다. 또한 동적 계산 그래프를 지원하여, 연산 과정이 Runtime에 결정되고 수정될 수 있게 해줍니다.
## 1.1. 리스트 데이터로 텐서 생성하기


In [2]:
import torch

ls = [1, 2, 3, 4, 5]
tensor1 = torch.tensor(ls)

print(tensor1)

tensor([1, 2, 3, 4, 5])


## 1.2. 넘파이 배열로 Tensor 생성하기

In [3]:
import numpy as np

numpy_array = np.array([1.5, 2.5, 3.5])
tensor2 = torch.tensor(numpy_array)

print(tensor2)

tensor([1.5000, 2.5000, 3.5000], dtype=torch.float64)


# 2. Data Type
### Tensor의 Type
Tensor의 Type(data type)은 Tensor가 저장하고 있는 data의 종류를 정의합니다. PyTorch에서는 다양한 data type을 지원하여, 다양한 종류의 data와 연산의 정밀도 요구사항을 충족시킵니다. data type은 Tensor의 각 요소가 차지하는 memory의 크기와 표현할 수 있는 값의 범위를 결정합니다. 
## 2.1. Integer Types
- torch.int8: 부호 없는 8비트 정수
- torch.unit8: 부호 없는 8비트 정수
- torch.int16 or torch.short: 16비트 정수
- torch.int64 or torch.long: 64비트 정수

In [4]:
# 정수형 텐서 생성
int_tensor = torch.tensor([1, 2, 3, 4])

print("정수형 텐서 값: ", int_tensor)
print("텐서의 타입: ", int_tensor.dtype)

정수형 텐서 값:  tensor([1, 2, 3, 4])
텐서의 타입:  torch.int64


## 2.2. Floating Point Types
- torch.float16 or torch.half: 16비트 반정밀도 부동 소수점
- torch.float32 or torch.float: 32비트 단정밀도 부동 소수점
- torch.float64 or torch.double: 64비트 배정밀도 부동 소수점
- torch.complex64: 32 비트 부동 소수점을 사용하는 복소수
- torch.complex128 or torch.cdouble: 64비트 부동 소수점을 사용하는 복소수

In [5]:
# 부동 소수점형 텐서 생성
float_tensor = torch.tensor([1.0, 2.0, 3.0, 4.0])

print("실수형 텐서 값: ", float_tensor)
print("텐서의 타입: ", float_tensor.dtype)

실수형 텐서 값:  tensor([1., 2., 3., 4.])
텐서의 타입:  torch.float32


## 2.3. Bool Type Tensor 생성
- torch.bool: True or False

In [6]:
bool_tensor = torch.tensor([True, False, True])

print("불리언 텐서 값: ", bool_tensor)
print("텐서의 타입: ", bool_tensor.dtype)

불리언 텐서 값:  tensor([ True, False,  True])
텐서의 타입:  torch.bool


## 2.4. 지정된 Data Type으로 Tensor 생성

In [7]:
specified_float_tensor = torch.tensor([1, 2, 3, 4], dtype=torch.float32)

print("타입 변환한 텐서 값: ", specified_float_tensor)
print("텐서의 타입: ",specified_float_tensor.dtype)

타입 변환한 텐서 값:  tensor([1., 2., 3., 4.])
텐서의 타입:  torch.float32


## 2.5. Tensor의 Type 변경 (1)

In [8]:
# 초기 텐서 생성 (정수 타입)
tensor = torch.tensor([1, 2, 3, 4])

# 텐서 속성 변환
float_tensor = tensor.float()           # int -> float
int_tensor = float_tensor.int()         # float -> int
double_tensor = float_tensor.double()   # float -> double
bool_tensor = int_tensor.bool()         # int -> bool

print("처음 생성한 텐서: ", tensor.dtype)
print('float_tensor의 타입 확인: ', float_tensor.dtype)
print('int_tensor의 타입 확인: ', int_tensor.dtype)
print('double_tensor의 타입 확인: ', double_tensor.dtype)
print('bool_tensor의 타입 확인: ', bool_tensor.dtype)

처음 생성한 텐서:  torch.int64
float_tensor의 타입 확인:  torch.float32
int_tensor의 타입 확인:  torch.int32
double_tensor의 타입 확인:  torch.float64
bool_tensor의 타입 확인:  torch.bool


## 2.6. Tensor의 타입 변경 (2) - to 메소드

In [9]:
# 텐서 속성 변환
float_tensor2 = tensor.to(dtype=torch.float32)
int_tensor2 = float_tensor.to(dtype=torch.int32)
double_tensor2 = float_tensor.to(dtype=torch.float64)
bool_tensor2 = int_tensor.to(dtype=torch.bool)

print("처음 생성한 텐서: ", tensor.dtype)
print('float_tensor의 타입 확인: ', float_tensor2.dtype)
print('int_tensor의 타입 확인: ', int_tensor2.dtype)
print('double_tensor의 타입 확인: ', double_tensor2.dtype)
print('bool_tensor의 타입 확인: ', bool_tensor2.dtype)

처음 생성한 텐서:  torch.int64
float_tensor의 타입 확인:  torch.float32
int_tensor의 타입 확인:  torch.int32
double_tensor의 타입 확인:  torch.float64
bool_tensor의 타입 확인:  torch.bool


# 3. Dimension and Shape
### Dimension
Dimension은 Tensor가 가지는 axis(축)의 수를 의미합니다. 차원의 수는 Tensor 데이터의 복잡성을 나타내며, 이는 Tensor가 얼마나 많은 수준의 중첩된 배열 구조를 가지고 있는지를 나타냅니다.
- 0차원 Tensor: scalar(단일 숫자)
- 1차원 Tensor: vector(숫자의 배열)
- 2차원 Tensor: matrix(숫자의 2차원 배열)
- 3차원 이상의 Tensor: 다차원 배열을 의미합니다.
### Shape
형태는 각 차원에서 텐서가 얼마나 많은 요소를 가지고 있는지를 나태나는 튜플입니다. 형태는 텐서의 구체적인 크기와 구조를 정의합니다. \
예를 들어, [3, 4] 형태의 2차원 텐서는 3개의 행과 4개의 열을 가진 행렬을 의미합니다. [2, 3, 4] 형태의 3차원 텐서는 2개의 3x4 행렬을 쌓아 놓은 구조를 가지고 있습니다. \
텐서의 형태는 데이터를 조작하고, 모델을 설계할 때 중요한 역할을 합니다. 예를 들어, 신경망의 입력 레이어는 입력 데이터의 형태에 따라 설계되어야 하며, 연산을 수행할 때 텐서의 형태가 올바르게 맞춰져 있어야 합니다.
### 코드 설명
- 차원 확인: tensor.dim() or len(tensor.shape)를 사용하여 Tensor의 차원을 확인할 수 있습니다.
- 형태 확인: tensor.shape or tensor.size()를 사용하여 Tensor의 형태(크기)를 확인할 수 있습니다.
## 3.1. Scalar

In [10]:
data = 5

scalar = torch.tensor(data)

print("스칼라: ", scalar)
print("스칼라 차원: ", scalar.dim())
print("스칼라 형태: ", scalar.shape)

스칼라:  tensor(5)
스칼라 차원:  0
스칼라 형태:  torch.Size([])


## 3.2. Vector 생성

In [12]:
data = [1, 2, 3]

vector = torch.tensor(data)

print("벡터: ", vector)
print("벡터 차원: ", vector.dim())
print("벡터 형태: ", vector.shape)

벡터:  tensor([1, 2, 3])
벡터 차원:  1
벡터 형태:  torch.Size([3])


## 3.3 Matrix (2차원 Tensor) 생성

In [13]:
data = [[1, 2, 3],
        [4, 5, 6]]

vector = torch.tensor(data)

print("벡터: ", vector)
print("벡터 차원: ", vector.dim())
print("벡터 형태: ", vector.shape)

벡터:  tensor([[1, 2, 3],
        [4, 5, 6]])
벡터 차원:  2
벡터 형태:  torch.Size([2, 3])


## 3.4. 3차원 Tensor 생성

In [17]:
data = [
    [[1, 2, 3],
     [3, 4, 5]],
    [[5, 6, 7],
     [7, 8, 8]]
    ]

tensor3D = torch.tensor(data)

print("3차원 텐서:\n", tensor3D)
print("3차원 텐서 차원: ", tensor3D.dim())
print("3차원 텐서 형태: ", tensor3D.shape)

3차원 텐서:
 tensor([[[1, 2, 3],
         [3, 4, 5]],

        [[5, 6, 7],
         [7, 8, 8]]])
3차원 텐서 차원:  3
3차원 텐서 형태:  torch.Size([2, 2, 3])


# 4. 텐서 생성 (1)
## 4.1. torch.zeros
지정된 크기로 모든 요소가 0인 Tensor를 생성합니다. 이는 가중치 초기화나 임시 Tensor 생성 시 유용하게 사용됩니다. 

In [16]:
zeros_tensor = torch.zeros(2, 3)
print("영(0) 텐서:\n", zeros_tensor)

영(0) 텐서:
 tensor([[0., 0., 0.],
        [0., 0., 0.]])


## 4.2. torch.ones
지정된 크기의 Tensor를 생성하고 모든 요소를 1로 채웁니다. 이는 종종 특정 연산에서의 기본값 설정이나, 마스킹 연산에서 사용됩니다.

In [18]:
ones_tensor = torch.ones(2, 3)
print("일(1) 텐서:\n", ones_tensor)

일(1) 텐서:
 tensor([[1., 1., 1.],
        [1., 1., 1.]])


## 4.3. torch.full
지정된 크기로 모든 요소를 사용자가 지정한 값으로 채운 Tensor를 생성합니다. 이는 특정 값으로 초기화된 Tensor가 필요할 때 사용됩니다.

In [19]:
full_tensor = torch.full((2, 3), 5)
print("Full 텐서:\n", full_tensor)

Full 텐서:
 tensor([[5, 5, 5],
        [5, 5, 5]])


## 4.4. torch.eye
단위 행렬(identity matrix)을 생성합니다. 주 대각선 요소가 모두 1이고 나머지 요소는 0인 정사각 행렬을 반환합니다.

In [20]:
eye_tensor = torch.eye(3)   # 3x3 단위 행렬 생성
print("\nIdentity Matrix (Eye Tensor):\n", eye_tensor)


Identity Matrix (Eye Tensor):
 tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])


## 4.5. torch.arange
시작값과 끝값, 그리고 선택적인 단계(step)값을 받아 이 범위 내에서 일정한 간격의 요소를 가진 1차원 Tensor를 생성합니다.

In [21]:
arange_tensor = torch.arange(0, 10, 2)  # 0부터 10 미만까지 2씩 증가
print("\nArange Tensor:\n", arange_tensor)


Arange Tensor:
 tensor([0, 2, 4, 6, 8])


## 4.6. torch.linspace
시작값과 끝값을 받고, 지정된 개수만큼의 요소를 이 두 값 사이에 균등하게 배치한 1차원 Tensor를 생성합니다.

In [22]:
linspace_tensor = torch.linspace(0, 10, 5)  # 0부터 10까지 5개의 요소를 균등하게 배치
print("\nLinspace Tensor:\n", linspace_tensor)


Linspace Tensor:
 tensor([ 0.0000,  2.5000,  5.0000,  7.5000, 10.0000])


# 5. Tensor 생성 (2) - Random data
PyTorch는 Random data를 생성하여 Tensor를 초기화하는 여러 함수를 제공합니다. \
이러한 함수들은 model을 학습하기 전 가중치 초기화, 데이터 셔플링 or 더미 데이터 생성 등 다양한 목적으로 사용됩니다. \
\
아래는 Random data를 생성하는 함수 입니다.
## 5.1. torch.rand
주어진 크기의 Tensor를 생성하고, 모든 요소를 0과 1 사이의 uniform distribution(균일 분포)에서 랜덤하게 채웁니다.\
이는 일반적으로 모델의 가중치 초기화에 사용됩니다.

In [23]:
rand_tensor = torch.rand(2, 3)
print("균일 분포 랜덤 텐서:\n", rand_tensor)

균일 분포 랜덤 텐서:
 tensor([[0.5107, 0.4466, 0.4256],
        [0.1200, 0.1447, 0.6996]])


## 5.2. torch.randn
주어진 크기의 Tensor를 생성하고, 모든 요소를 평균 0과 표준편차 1을 가진 normal distribution(정규 분포)에서 랜덤하게 채웁니다.\
이 함수는 가중치 초기화 or 노이즈 추가 등에 유용하게 사용됩니다.

In [24]:
randn_tensor = torch.randn(2, 3)
print("정규 분포 랜덤 텐서:\n", randn_tensor)

정규 분포 랜덤 텐서:
 tensor([[ 0.7129, -0.2696,  0.1592],
        [-0.3640,  0.6517, -0.1771]])


## 5.3. randint
지정된 범위 내에서 랜덤한 정수를 생성하여 텐서를 초기화합니다. \
이 함수는 정수 값을 가진 Tensor를 필요로 할 때, 예를 들어 index를 랜덤하게 생성할 때 유용합니다.

In [25]:
randint_tensor = torch.randint(low=0, high=10, size=(2, 3))
print("정수 랜덤 텐서:\n", randint_tensor)

정수 랜덤 텐서:
 tensor([[1, 6, 3],
        [8, 3, 4]])


## 5.4. torch.randperm
0부터 n-1까지의 정수를 랜덤하게 섞어서 반환합니다. 이는 dataset을 shuffling할 때 주로 사용됩니다.

In [26]:
randperm_tensor = torch.randperm(10)    # 0부터 9까지의 숫자를 random하게 섞음
print("랜덤 순열(Permutation) 텐서:\n", randperm_tensor)

랜덤 순열(Permutation) 텐서:
 tensor([3, 0, 5, 1, 8, 6, 9, 4, 2, 7])
