# Stage 5. Linear Algebra

# 1. 곱셈 연산
## 1.1 Vector 곱셈 (점곱, Dot Product)
Dot Product는 두 Vector 간의 연산으로, 각 Vector의 상응하는 성분들을 곱한 뒤 그 결과들을 모두 더해 하나의 Scalar 값으로 반환합니다.  
이 연산은 두 Vector의 내적을 계산하는 것과 동일합니다.

Vector의 곱셈은 다음과 같이 계산합니다.

$$
a = \begin{bmatrix}
a_1 \\
a_2 \\
\vdots \\
a_n
\end{bmatrix}, \quad
b = \begin{bmatrix}
b_1 \\
b_2 \\
\vdots \\
b_n
\end{bmatrix}
$$

$$
a \cdot b = \sum_{i=1}^{n} a_i b_i = a_1 b_1 + a_2 b_2 + \cdots + a_n b_n
$$

In [2]:
import torch

# Vector 정의
vector1 = torch.tensor([1, 2, 3])
vector2 = torch.tensor([4, 5, 6])

# Vector의 내적 계산
dot_product = vector1 @ vector2
# 또는 torch.dot(vector1, vector2) 로 내적을 계산할 수 있다.

print("벡터의 내적 결과:", dot_product) 
# 출력이 32인 이유: 1*4 + 2*5 + 3*6 = 32

벡터의 내적 결과: tensor(32)


## 1.2 행렬의 곱셈

행렬 $A$와 행렬 $B$의 곱셈 $AB$를 고려해봅시다.  
$A$가 $m \times n$ 행렬이고 $B$가 $n \times p$ 행렬일 때,  
두 행렬의 곱은 $m \times p$ 행렬 $C$가 됩니다.  

행렬 $C$의 각 요소 $c_{ij}$는 다음과 같이 계산됩니다.

$$
c_{ij} = \sum_{k=1}^{n} a_{ik} \cdot b_{kj}
$$

구체적으로는 아래와 같이 계산하면 됩니다.

$$
A = \begin{bmatrix}
a_{11} & a_{12} & a_{13} \\
a_{21} & a_{22} & a_{23}
\end{bmatrix}, \quad
B = \begin{bmatrix}
b_{11} & b_{12} \\
b_{21} & b_{22} \\
b_{31} & b_{32}
\end{bmatrix}
$$

이때, 행렬 곱은

$$
AB = \begin{bmatrix}
a_{11}b_{11} + a_{12}b_{21} + a_{13}b_{31} & a_{11}b_{12} + a_{12}b_{22} + a_{13}b_{32} \\
a_{21}b_{11} + a_{22}b_{21} + a_{23}b_{31} & a_{21}b_{12} + a_{22}b_{22} + a_{23}b_{32}
\end{bmatrix}
$$


In [3]:
# 두 개의 2x2 행렬을 정의합니다.
matrix1 = torch.tensor([[1, 2], [3, 4]])
matrix2 = torch.tensor([[5, 6], [7, 8]])

# 행렬 곱셈 연산을 수행합니다.
mul_matrix = torch.matmul(matrix1, matrix2)

print("행렬 matrix1:\n", matrix1)
print("행렬 matrix2:\n", matrix2)
print("matrix1와 matrix2의 곱 mul_matrix:\n", mul_matrix)

행렬 matrix1:
 tensor([[1, 2],
        [3, 4]])
행렬 matrix2:
 tensor([[5, 6],
        [7, 8]])
matrix1와 matrix2의 곱 mul_matrix:
 tensor([[19, 22],
        [43, 50]])


# 2. Determinant (행렬 식)
### 행렬식이란
행렬식의 값은 행렬이 **역행렬**을 가지는지 여부를 결정합니다. 행렬식이 0이 아니면 행렬은 역행렬을 가지며, 행렬식이 0이면 행렬은 역행렬을 가지지 않습니다.\
\
또한, 행렬식은 모든 열(또는 행)이 생성하는 공간의 부피를 나타내며, 행렬이 선형 변환을 수행할 때 공간이 얼마나 확장 또는 축소되는지를 나타냅니다. 이는 행렬이 선형 독립인 열(또는 행)을 가지고 있는지 여부를 판단하는 데도 사용됩니다.\
\
PyTorch에서는 torch.linalg.det() 함수를 사용하여 주어진 행렬의 행렬식을 계산합니다.

### 행렬식
$2\times2$ 행렬의 경우, 행렬식은 다음과 같습니다.
$$
\det(A) = ad - bc
$$
그 외 일반적인 행렬의 행렬식은 다음과 같습니다.
$$
\det(A) = \sum_{j=1}^{n} (-1)^{i+j} a_{ij} \cdot \det(A_{ij})
$$
$a_{ij}$는 A의 i행 j열에 위치한요소. $A_{ij}$는 $a_{ij}$를 제외한 행렬에서 i행과 j열을 제거하여 얻은 부분 행렬

## 2.1. 행렬식 1

In [4]:
matrix_A = torch.tensor([[4, 7], [2, 6]], dtype=torch.float32)

# 행렬식 계산
det_A = torch.linalg.det(matrix_A)

print(f"A 행렬의 행렬식: {det_A}")
print('직접 계산: ', 4*6 - 7*2)  # 직접 계산: 10.0

A 행렬의 행렬식: 10.000000953674316
직접 계산:  10


## 2.2. 행렬식 예제 2
- 행렬식이 0인 경우

In [5]:
# 3x3 행렬 정의
matrix_B = torch.tensor(
    [[1, 2, 3],
     [4, 5, 6],
     [7, 8, 9]], dtype=torch.float32)

# 행렬식 계산
det_B = torch.linalg.det(matrix_B)
print(f"B 행렬의 행렬식: {det_B}")

B 행렬의 행렬식: 0.0


# 3. 역행렬
Inverse Matrix (역행렬)은 선형 대수학에서 주어진 행렬 A에 대해, A와 곱했을 때 항등 행렬 I를 생성하는 행렬을 말합니다.\
\
식으로 표현하면 아래와 같습니다.
$$
A \times A^{-1} = A^{-1} \times A = I
$$
항등 행렬 I는 모든 대각선 상의 원소가 1이고, 그 외의 원소는 모두 0인 행렬을 의미합니다.\
\
항등 행렬을 식으로 표현하면 아래와 같습니다.
$$
I =
\begin{pmatrix}
1 & 0 & \cdots & 0 \\
0 & 1 & \cdots & 0 \\
\vdots & \vdots & \ddots & \vdots \\
0 & 0 & \cdots & 1
\end{pmatrix}
$$
## 3.1. 역행렬 계산

In [7]:
# 가역적인 2x2 행렬 정의
matrix_A = torch.tensor([[4.0, 7.0], [2.0, 6.0]])

# 역행렬 계산
matrix_inv = torch.linalg.inv(matrix_A)

print("matrix_A 행렬:\n", matrix_A)
print("matrix_A의 역행렬:\n", matrix_inv)

matrix_A 행렬:
 tensor([[4., 7.],
        [2., 6.]])
matrix_A의 역행렬:
 tensor([[ 0.6000, -0.7000],
        [-0.2000,  0.4000]])


## 3.2. 역행렬 식 확인해보기 (1)
$A \times A^{-1} = I$ 식이 맞는지 확인해 봅시다.

In [8]:
# A x A-1 가 항등 행렬인지 확인해 봅시다.
torch.matmul(matrix_A, matrix_inv)

tensor([[1., 0.],
        [0., 1.]])

## 3.3. 역행렬 식 확인해보기 (2)
$A^{-1} \times A = I$ 식이 맞는지 확인해 봅시다.

In [9]:
# A-1 x A가 항등 행렬인지 확인해 봅시다.
torch.matmul(matrix_inv, matrix_A)

tensor([[1., 0.],
        [0., 1.]])

## 3.4. 행렬식이 0일 때, 역행렬 연산

In [11]:
matrix = torch.tensor(
    [[1, 2, 3],
     [4, 5, 6],
     [7, 8, 9]], dtype=torch.float32)

det = torch.linalg.det(matrix)
print(f"matrix 행렬의 행렬식: {det}")

matrix 행렬의 행렬식: 0.0


In [12]:
try:
    torch.linalg.inv(matrix)
except Exception as e:
    print(e) # 행렬식이 0일 때, 역행렬을 구하면 에러가 발생하는 것을 확인할 수 있음.

linalg.inv: The diagonal element 3 is zero, the inversion could not be completed because the input matrix is singular.


# 4. Trace
### Trace란?
Trace는 선형대수학에서 사용되는 용어로, 주로 정사각형 행렬에 대해 정의됩니다. Trace는 행렬의 diagonal(주대각선) 상의 모든 원소의 합으로 계산됩니다. 즉, 행렬 A의 Trace는 A의 i번째 행과 i번째 열이 만나는 위치의 원소들 $a_{ii}$의 합으로 표현됩니다.\
수학적으로는 다음과 같이 표현됩니다.
$$
Tr(A) = \sum_{i=1}^{n}a_{ii}
$$
torch.trace() 함수를 이용하면 Trace 연산을 수행할 수 있습니다.
### 주의할 점
- torch.trace() 함수는 주로 2D Tensor에 사용됩니다. 만약 더 높은 차원의 Tensor를 입력으로 사용한다면, 함수는 내부적으로 Tensor의 마지막 두 차원에 대해 Trace 연산을 수행합니다.

- 행렬의 Trace는 행렬이 정사각형일 때 가장 의미가 있습니다. 비정사각형 행렬의 경우에도 대각선 원소들의 합은 계산되지만, Trace가 가지는 선형대수학적 의미는 다를 수 있습니다.

In [13]:
# 정사각 행렬 정의
A = torch. tensor([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]], dtype=torch.float)

# 행렬의 트레이스 계산
trace_A = torch.trace(A)
print(f"A 행렬의 Trace: {trace_A}")  # 출력: 15.0 (1 + 5 + 9)

A 행렬의 Trace: 15.0
