# Stage 5. Linear Algebra

# 1. 곱셈 연산
## 1.1 Vector 곱셈 (점곱, Dot Product)
Dot Product는 두 Vector 간의 연산으로, 각 Vector의 상응하는 성분들을 곱한 뒤 그 결과들을 모두 더해 하나의 Scalar 값으로 반환합니다.  
이 연산은 두 Vector의 내적을 계산하는 것과 동일합니다.

Vector의 곱셈은 다음과 같이 계산합니다.

$$
a = \begin{bmatrix}
a_1 \\
a_2 \\
\vdots \\
a_n
\end{bmatrix}, \quad
b = \begin{bmatrix}
b_1 \\
b_2 \\
\vdots \\
b_n
\end{bmatrix}
$$

$$
a \cdot b = \sum_{i=1}^{n} a_i b_i = a_1 b_1 + a_2 b_2 + \cdots + a_n b_n
$$

In [ ]:
import torch

# Vector 정의
vector1 = torch.tensor([1, 2, 3])
vector2 = torch.tensor([4, 5, 6])

# Vector의 내적 계산
dot_product = vector1 @ vector2
# 또는 torch.dot(vector1, vector2) 로 내적을 계산할 수 있다.

print("벡터의 내적 결과:", dot_product) 
# 출력이 32인 이유: 1*4 + 2*5 + 3*6 = 32

벡터의 내적 결과: 32


## 1.2 행렬의 곱셈

행렬 $A$와 행렬 $B$의 곱셈 $AB$를 고려해봅시다.  
$A$가 $m \times n$ 행렬이고 $B$가 $n \times p$ 행렬일 때,  
두 행렬의 곱은 $m \times p$ 행렬 $C$가 됩니다.  

행렬 $C$의 각 요소 $c_{ij}$는 다음과 같이 계산됩니다.

$$
c_{ij} = \sum_{k=1}^{n} a_{ik} \cdot b_{kj}
$$

구체적으로는 아래와 같이 계산하면 됩니다.

$$
A = \begin{bmatrix}
a_{11} & a_{12} & a_{13} \\
a_{21} & a_{22} & a_{23}
\end{bmatrix}, \quad
B = \begin{bmatrix}
b_{11} & b_{12} \\
b_{21} & b_{22} \\
b_{31} & b_{32}
\end{bmatrix}
$$

이때, 행렬 곱은

$$
AB = \begin{bmatrix}
a_{11}b_{11} + a_{12}b_{21} + a_{13}b_{31} & a_{11}b_{12} + a_{12}b_{22} + a_{13}b_{32} \\
a_{21}b_{11} + a_{22}b_{21} + a_{23}b_{31} & a_{21}b_{12} + a_{22}b_{22} + a_{23}b_{32}
\end{bmatrix}
$$


In [4]:
# 두 개의 2x2 행렬을 정의합니다.
matrix1 = torch.tensor([[1, 2], [3, 4]])
matrix2 = torch.tensor([[5, 6], [7, 8]])

# 행렬 곱셈 연산을 수행합니다.
mul_matrix = torch.matmul(matrix1, matrix2)

print("행렬 matrix1:\n", matrix1)
print("행렬 matrix2:\n", matrix2)
print("matrix1와 matrix2의 곱 mul_matrix:\n", mul_matrix)

행렬 matrix1:
 tensor([[1, 2],
        [3, 4]])
행렬 matrix2:
 tensor([[5, 6],
        [7, 8]])
matrix1와 matrix2의 곱 mul_matrix:
 tensor([[19, 22],
        [43, 50]])


# 2. Determinant (행렬 식)
### 행렬식이란
행렬식의 값은 행렬이 **역행렬**을 가지는지 여부를 결정합니다. 행렬식이 0이 아니면 행렬은 역행렬을 가지며, 행렬식이 0이면 행렬은 역행렬을 가지지 않습니다.\
\
또한, 행렬식은 모든 열(또는 행)이 생성하는 공간의 부피를 나타내며, 행렬이 선형 변환을 수행할 때 공간이 얼마나 확장 또는 축소되는지를 나타냅니다. 이는 행렬이 선형 독립인 열(또는 행)을 가지고 있는지 여부를 판단하는 데도 사용됩니다.\
\
PyTorch에서는 torch.linalg.det() 함수를 사용하여 주어진 행렬의 행렬식을 계산합니다.

### 행렬식
$2\times2$ 행렬의 경우, 행렬식은 다음과 같습니다.
$$
\det(A) = ad - bc
$$
그 외 일반적인 행렬의 행렬식은 다음과 같습니다.
$$
\det(A) = \sum_{j=1}^{n} (-1)^{i+j} a_{ij} \cdot \det(A_{ij})
$$
$a_{ij}$는 A의 i행 j열에 위치한요소. $A_{ij}$는 $a_{ij}$를 제외한 행렬에서 i행과 j열을 제거하여 얻은 부분 행렬

## 2.1. 행렬식 1